name: Test Workflow

on:
  push:
    branches: [ master ]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Print Hello
        run: echo "✅ GitHub Actions is working!"
